.github/ISSUE_TEMPLATE/add-new-tool.md, .github/ISSUE_TEMPLATE/bug-report.md, .github/pull_request_template.md, .gitignore, COMMIT_GUIDELINES.md, CONTRIBUTING.md, CONTRIBUTOR_EXAMPLE.md, LICENSE, README.md, assets/README.md, assets/favicon.svg, assets/og-image.svg, contributors.json, index.html, manifest.json, robots.txt, script.js, sitemap.xml, style.css
- Restructure from basic link manager to comprehensive AI tools hub
- Add complete open-source project structure with templates and guidelines
- Implement modern UI with Tailwind CSS and responsive design
- Add SEO optimization with meta tags and structured data
- Create contributor system with GitHub integration
- Add category filtering and search functionality
- Implement Google Analytics tracking for user engagement
- Add comprehensive documentation (README, CONTRIBUTING, COMMIT_GUIDELINES)
- Create GitHub issue templates and PR template
- Add professional assets (favicon, OG images, manifest)
- Update About section with two-column layout for creator and community
- Add Meerut Coders community integration
BREAKING CHANGE: Complete project restructure from simple HTML page to …
=> feat: transform project into professional AI tools directory

contributors.json, script.js
**Tool Name:**
**Category:**
**Why it's valuable:**
**Free tier confirmed:** Yes/No
___
Enhancement
___
- Enhanced contributor profiles with LinkedIn integration
- Added tagline support for contributor descriptions
- Improved social media button styling and layout
- Updated contributor data with new profile fields
___
```mermaid
flowchart LR
A["Contributor Profile"] --> B["Add LinkedIn Field"]
A --> C["Add Tagline Field"]
B --> D["Social Media Buttons"]
C --> D
D --> E["Enhanced Profile Display"]
```
<details> <summary><h3> File Walkthrough</h3></summary>
<table><thead><tr><th></th><th align="left">Relevant …
=> feat(contributors): enhance contributor profiles with LinkedIn and taglines

contributors.json, links.json
**Tool Name:** Google AI Studio
**Category:**  AI Model Prototyping
**Why it's valuable:** WEB based IDE
**Free tier confirmed:** **Yes**/No
___
Enhancement
___
- Added new contributor Taranpreet Singh to contributors list
- Created new "AI Model Prototyping" category with Google AI Studio
- Expanded tool collection with developer-focused AI prototyping tools
___
```mermaid
flowchart LR
A["New Contributor"] --> B["Taranpreet Singh"]
C["New Category"] --> D["AI Model Prototyping"]
E["New Tool"] --> F["Google AI Studio"]
B --> G["Contributors List"]
D --> H["Links Collection"]
F --> H
```
<details> <summary><h3> File Walkthrough</h3></summary> …
=> refactor(tool): add new tool with new category AI Model Prototyping: Google AI Studio

contributors.json, links.json
Enhancement
___
- Added new AI Game & Strategy category with Chess Champ tool
- Added contributor Chirag Tankan to contributors list
___
```mermaid
flowchart LR
A["New Contributor"] --> B["Chirag Tankan"]
B --> C["Chess Champ Tool"]
C --> D["AI Game & Strategy Category"]
```
<details> <summary><h3> File Walkthrough</h3></summary>
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>contributors.json</strong><dd><code>Add Chirag Tankan as contributor</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
contributors.json …
=> MERGE REQUEST PRODUCTION

contributors.json, links.json
📄 Description:
This PR introduces a new "AI Local Models" category under AI Tools, making it easier for developers to discover tools that allow running large language models locally without cloud dependency.
The following tools were added:
[GPT4All](https://gpt4all.io/)
– Run open-source LLMs locally on your computer.
[Ollama](https://ollama.ai/)
– Simple way to run and manage LLMs locally.
[LM Studio](https://lmstudio.ai/)
– Desktop app to run and chat with local models.
[Llama.cpp](https://github.com/ggerganov/llama.cpp)
– Local inference of LLaMA models on CPU/GPU.
[AnythingLLM](https://anything-llm.org/)
– Toolkit to run and connect many local LLMs.
[Jan](https://jan.ai/)
– Open-source local ChatGPT alternative.
**Free to Use** 
Additionally:
Updated contributors.json with my …
=> add Local LLMs category with tools

index.html, script.js
A brief description of what this PR does.
=> feat(ui): redesign contributors section with modern layout

contributors.json, links.json
I added the 'Monica' AI tool under the AI Writing & Content category. It's one of the most widely used free AI tools.
**Tool Name:** Monica
**Category:** AI Writing & Content
**Why it's valuable:** It's a free AI tool used by 10,000,000+ user, it has 4,9 rating in Chrome Web Store.
=> Added "Monica" under the AI Writing & Content category

index.html, script.js
- Hide GitHub button and theme toggle on mobile for cleaner nav
- Simplify mobile menu with better animations and touch targets
- Convert back-to-top button to use Tailwind classes instead of custom CSS
- Add primary color styling with shadow effects for better visibility
- Improve responsive design and accessibility
=> feat: improve mobile navbar and back-to-top button

contributors.json
This pr adds my social links to the contributor lists. 
**Tool Name:**
**Category:**
**Why it's valuable:**
**Free tier confirmed:** Yes/No
=> docs/ added social links in contributor list

contributors.json, links.json
Add Simplified AI Writer, a free AI-powered content creation tool, to the AI Writing & Content category.
- **Tool Name**: Simplified AI Writer
- **Category**: AI Writing & Content
- **Why it's valuable**: Offers comprehensive free tier for generating content across blogs, social media, emails, and marketing copy
- **Free tier confirmed**: Yes
=> Something like "feat(tools): add Simplified AI Writer to AI Writing & Content category"

contributors.json, links.json
This PR adds AI-powered Zoho Show, a presentation maker. Its Zia AI can be used to build PPTs.
**Tool Name:** Zoho Show Zia AI
**Category:** AI Presentations
**Why it's valuable:** It helps build presentations easily with AI.
=> Added Zoho Show's Zia AI

style.css
Fixed persistent focus outline issue on buttons in the header and footer. Improved accessibility by implementing proper focus states for keyboard navigation while removing unwanted outlines from mouse clicks.
**BEFORE**
**AFTER**
@ArshdeepGrover 
**Please label for Hacktoberfest**
=> Fixed the persistent blue outline over the buttons when clicked

contributors.json, links.json
**Tool Name:*Promptly Ai*
**Category:*AI Writing*
**Why it's valuable:*One-click prompt optimization, prompt library & chat export tool for ChatGPT / Claude / Perplexity*
=> add: promptly ai to ai tools collection

index.html, script.js, style.css
This PR adds a smooth scrolling behavior to the contributors section. When users click the "Show Less" button to collapse the expanded list of contributors, the page automatically scrolls back to the top of the contributors section for better user experience.
- Modified `toggleShowAllContributors()` function in `script.js`
- Added `scrollIntoView` with smooth behavior when `showAllContributors` is set to `false`
- Used `setTimeout` to ensure DOM updates complete before scrolling
- Verified no conflicts with existing scroll behaviors (anchor links, back-to-top button)
- Smooth scrolling works consistently across browsers
=> Add scroll show less

README.md, contributors.json, index.html, links.json
i added 2 tools poe and gemini , and on some browsers tailwindcss was not working so Fixed that Also , by adding browser4 version 
- [✔ ] New AI tool addition
- [✔ ] Bug fix
**Gemini**
**AI Writing & Content**
**A powerful, multimodal AI model by Google.**
**poe**
**AI Writing & Content**
**An AI platform to chat with a variety of bots like ChatGPT, Claude, and more.**
- [✔ ] Added new tool to `links.json`
- [✔ ] Updated `contributors.json` with my information
- [✔ ] Tested changes locally
- [✔ ] Verified tool is not a duplicate
- [✔ ] Ensured tool has free tier
- [✔ ] I have tested these changes locally
- [✔ ] The website loads correctly
- [✔ ] All links work properly
- [ ✔] Mobile responsiveness is maintained
Add screenshots of …
=> added 2 tools and on some browsers tailwindcss was not working so Fixed that Also

README.md, contributors.json, index.html, links.json, package-lock.json
**Tool Name:**
**Category:**
**Why it's valuable:**
**Free tier confirmed:** Yes/No
=> fix: contributors grid array (#95)

index.html, style.css
Again created a new branch and raised a new pr and published the branch
=> changed navbar again

contributors.json, links.json
total 6 more tools added in 2 category and Updated Contribution according to that tools 
- [✔ ] New AI tool addition
**Tool Name: Codeium
Category: AI Coding & Development
Why it's valuable: An AI assistant that integrates directly into your IDE to provide intelligent code completion and assistance.
Free tier confirmed: Yes
Tool Name: Replit Ghostwriter
Category: AI Coding & Development
Why it's valuable: Acts as an AI coding companion within the Replit environment, helping to generate, explain, and debug code.
Free tier confirmed: Yes
Tool Name: Mutable AI
Category: AI Coding & Development
Why it's valuable: Specializes in modernizing legacy code by automatically refactoring it and generating up-to-date documentation.
Free tier confirmed: Yes
Tool Name: Continue
Category: AI Coding & …
=> total 6 more tools has been added in 2 category , and updated Contribution

.github/workflows/check-duplicates.yml, .github/workflows/validate-data.yml, validate-links.js
**Tool Name:**
**Category:**
**Why it's valuable:**
**Free tier confirmed:** Yes/No
=> fix(workflows): check duplicate and validate data

script.js
Fixed the ReferenceError in the filterByCategory() function caused by using an undefined variable button instead of the loop variable btn.
Updated all occurrences to ensure correct variable usage and consistent event handling.
Changes made:
* Replaced button with btn inside the forEach loop.
* Ensured proper styling and hover effects for category buttons.
* Verified that category filtering now works smoothly without any runtime errors.
@ArshdeepGrover let me know if some change is required.
=> Fixed the ReferenceError in the filterByCategory() function

contributors.json, links.json
This PR adds 2 new AI tools on the category which were given least importance to the ai-tools-manager repository for Hacktoberfest 2025. 
- New AI tool addition
**Tool Name:** Infinite Craft
**Category:** AI-powered sandbox crafting game
**Why it's valuable:** It offers endless creative discovery by combining elements to make anything imaginable.
**Tool Name:** ChatSlide AI
**Category:** AI presentation generator
**Why it's valuable:** Lets you upload multiple files—like PDFs, images, or even links—and turns them into clean, professional slides or videos
- Added new tool to `links.json`
- Updated `contributors.json` with my information
- Tested changes locally
- Verified tool is not a duplicate
- Ensured tool has free tier
- I have …
=> Add 2 new AI Tools
